# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(663, 716)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.tabWidget_PARENT = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_PARENT.setObjectName("tabWidget_PARENT")
        self.tab_INFO = QtWidgets.QWidget()
        self.tab_INFO.setObjectName("tab_INFO")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_INFO)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_API_Token = QtWidgets.QLabel(self.tab_INFO)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_API_Token.sizePolicy().hasHeightForWidth())
        self.label_API_Token.setSizePolicy(sizePolicy)
        self.label_API_Token.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.label_API_Token.setFont(font)
        self.label_API_Token.setObjectName("label_API_Token")
        self.gridLayout_13.addWidget(self.label_API_Token, 0, 0, 1, 1)
        self.lineEdit_API_Token = QtWidgets.QLineEdit(self.tab_INFO)
        self.lineEdit_API_Token.setObjectName("lineEdit_API_Token")
        self.gridLayout_13.addWidget(self.lineEdit_API_Token, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_INFO_QPU_List = QtWidgets.QComboBox(self.tab_INFO)
        self.comboBox_INFO_QPU_List.setEnabled(False)
        self.comboBox_INFO_QPU_List.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.comboBox_INFO_QPU_List.setEditable(False)
        self.comboBox_INFO_QPU_List.setCurrentText("")
        self.comboBox_INFO_QPU_List.setMinimumContentsLength(0)
        self.comboBox_INFO_QPU_List.setModelColumn(0)
        self.comboBox_INFO_QPU_List.setObjectName("comboBox_INFO_QPU_List")
        self.gridLayout_2.addWidget(self.comboBox_INFO_QPU_List, 4, 0, 1, 1)
        self.pushButton_INFO_Get_Info_on_Qubit = QtWidgets.QPushButton(self.tab_INFO)
        self.pushButton_INFO_Get_Info_on_Qubit.setEnabled(False)
        self.pushButton_INFO_Get_Info_on_Qubit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_INFO_Get_Info_on_Qubit.setObjectName("pushButton_INFO_Get_Info_on_Qubit")
        self.gridLayout_2.addWidget(self.pushButton_INFO_Get_Info_on_Qubit, 4, 1, 1, 2)
        self.label_INFO_QPU_Select = QtWidgets.QLabel(self.tab_INFO)
        self.label_INFO_QPU_Select.setObjectName("label_INFO_QPU_Select")
        self.gridLayout_2.addWidget(self.label_INFO_QPU_Select, 2, 0, 2, 1)
        self.horizontalSlider_INFO_Num_of_Qubits = QtWidgets.QSlider(self.tab_INFO)
        self.horizontalSlider_INFO_Num_of_Qubits.setEnabled(False)
        self.horizontalSlider_INFO_Num_of_Qubits.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_INFO_Num_of_Qubits.setMaximum(0)
        self.horizontalSlider_INFO_Num_of_Qubits.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_INFO_Num_of_Qubits.setObjectName("horizontalSlider_INFO_Num_of_Qubits")
        self.gridLayout_2.addWidget(self.horizontalSlider_INFO_Num_of_Qubits, 1, 1, 1, 2)
        self.label_INFO_Selected_Qubit = QtWidgets.QLabel(self.tab_INFO)
        self.label_INFO_Selected_Qubit.setObjectName("label_INFO_Selected_Qubit")
        self.gridLayout_2.addWidget(self.label_INFO_Selected_Qubit, 2, 2, 2, 1)
        self.label_INFO_Num_of_Qubits = QtWidgets.QLabel(self.tab_INFO)
        self.label_INFO_Num_of_Qubits.setObjectName("label_INFO_Num_of_Qubits")
        self.gridLayout_2.addWidget(self.label_INFO_Num_of_Qubits, 0, 1, 1, 2)
        self.label_INFO_qubits = QtWidgets.QLabel(self.tab_INFO)
        self.label_INFO_qubits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_INFO_qubits.setObjectName("label_INFO_qubits")
        self.gridLayout_2.addWidget(self.label_INFO_qubits, 2, 1, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 5, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_2, 0, 2, 5, 1)
        self.label_Chennel = QtWidgets.QLabel(self.tab_INFO)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.label_Chennel.setFont(font)
        self.label_Chennel.setObjectName("label_Chennel")
        self.gridLayout_13.addWidget(self.label_Chennel, 1, 0, 1, 1)
        self.lineEdit_Channel = QtWidgets.QLineEdit(self.tab_INFO)
        self.lineEdit_Channel.setObjectName("lineEdit_Channel")
        self.gridLayout_13.addWidget(self.lineEdit_Channel, 1, 1, 1, 1)
        self.label_Instance = QtWidgets.QLabel(self.tab_INFO)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.label_Instance.setFont(font)
        self.label_Instance.setObjectName("label_Instance")
        self.gridLayout_13.addWidget(self.label_Instance, 2, 0, 1, 1)
        self.lineEdit_Instance = QtWidgets.QLineEdit(self.tab_INFO)
        self.lineEdit_Instance.setObjectName("lineEdit_Instance")
        self.gridLayout_13.addWidget(self.lineEdit_Instance, 2, 1, 2, 1)
        self.pushButton_Apply_API_Token = QtWidgets.QPushButton(self.tab_INFO)
        self.pushButton_Apply_API_Token.setEnabled(False)
        self.pushButton_Apply_API_Token.setObjectName("pushButton_Apply_API_Token")
        self.gridLayout_13.addWidget(self.pushButton_Apply_API_Token, 3, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab_INFO)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.radioButton_PROFESSIONAL = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_PROFESSIONAL.setChecked(False)
        self.radioButton_PROFESSIONAL.setObjectName("radioButton_PROFESSIONAL")
        self.gridLayout_12.addWidget(self.radioButton_PROFESSIONAL, 2, 0, 1, 1)
        self.radioButton_BASE = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_BASE.setChecked(True)
        self.radioButton_BASE.setObjectName("radioButton_BASE")
        self.gridLayout_12.addWidget(self.radioButton_BASE, 1, 0, 1, 1)
        self.label_BaseProfi = QtWidgets.QLabel(self.frame_3)
        self.label_BaseProfi.setObjectName("label_BaseProfi")
        self.gridLayout_12.addWidget(self.label_BaseProfi, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_3, 4, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.tab_INFO)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_QPU_Available = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_QPU_Available.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_QPU_Available.setObjectName("pushButton_QPU_Available")
        self.horizontalLayout_6.addWidget(self.pushButton_QPU_Available)
        self.pushButton_QPU_Characteristics = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_QPU_Characteristics.setEnabled(False)
        self.pushButton_QPU_Characteristics.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_QPU_Characteristics.setObjectName("pushButton_QPU_Characteristics")
        self.horizontalLayout_6.addWidget(self.pushButton_QPU_Characteristics)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.pushButton_INFO_Clear_Output = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_INFO_Clear_Output.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_INFO_Clear_Output.setObjectName("pushButton_INFO_Clear_Output")
        self.verticalLayout_6.addWidget(self.pushButton_INFO_Clear_Output)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Console_Output = QtWidgets.QLabel(self.frame_2)
        self.label_Console_Output.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_Console_Output.setObjectName("label_Console_Output")
        self.verticalLayout.addWidget(self.label_Console_Output)
        self.textEdit_Console_Output = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_Console_Output.setEnabled(True)
        self.textEdit_Console_Output.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.textEdit_Console_Output.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_Console_Output.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_Console_Output.setReadOnly(True)
        self.textEdit_Console_Output.setObjectName("textEdit_Console_Output")
        self.verticalLayout.addWidget(self.textEdit_Console_Output)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_2, 5, 0, 1, 3)
        self.tabWidget_PARENT.addTab(self.tab_INFO, "")
        self.tab_INIT_IDLE_H = QtWidgets.QWidget()
        self.tab_INIT_IDLE_H.setObjectName("tab_INIT_IDLE_H")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_INIT_IDLE_H)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_TAB2_QPU_List = QtWidgets.QLabel(self.tab_INIT_IDLE_H)
        self.label_TAB2_QPU_List.setObjectName("label_TAB2_QPU_List")
        self.verticalLayout_12.addWidget(self.label_TAB2_QPU_List)
        self.comboBox_TAB2_QPU_List = QtWidgets.QComboBox(self.tab_INIT_IDLE_H)
        self.comboBox_TAB2_QPU_List.setEnabled(False)
        self.comboBox_TAB2_QPU_List.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_TAB2_QPU_List.setObjectName("comboBox_TAB2_QPU_List")
        self.verticalLayout_12.addWidget(self.comboBox_TAB2_QPU_List)
        self.verticalLayout_18.addLayout(self.verticalLayout_12)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem1)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_TAB2_JobID = QtWidgets.QLabel(self.tab_INIT_IDLE_H)
        self.label_TAB2_JobID.setAlignment(QtCore.Qt.AlignCenter)
        self.label_TAB2_JobID.setObjectName("label_TAB2_JobID")
        self.verticalLayout_17.addWidget(self.label_TAB2_JobID)
        self.lineEdit_TAB2_JobID = QtWidgets.QLineEdit(self.tab_INIT_IDLE_H)
        self.lineEdit_TAB2_JobID.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_TAB2_JobID.setClearButtonEnabled(True)
        self.lineEdit_TAB2_JobID.setObjectName("lineEdit_TAB2_JobID")
        self.verticalLayout_17.addWidget(self.lineEdit_TAB2_JobID)
        self.pushButton_TAB2_JobID_Info = QtWidgets.QPushButton(self.tab_INIT_IDLE_H)
        self.pushButton_TAB2_JobID_Info.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_TAB2_JobID_Info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_TAB2_JobID_Info.setObjectName("pushButton_TAB2_JobID_Info")
        self.verticalLayout_17.addWidget(self.pushButton_TAB2_JobID_Info)
        self.pushButton_TAB2_JobID_Cancell = QtWidgets.QPushButton(self.tab_INIT_IDLE_H)
        self.pushButton_TAB2_JobID_Cancell.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_TAB2_JobID_Cancell.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_TAB2_JobID_Cancell.setObjectName("pushButton_TAB2_JobID_Cancell")
        self.verticalLayout_17.addWidget(self.pushButton_TAB2_JobID_Cancell)
        self.pushButton_TAB2_JobID_Result = QtWidgets.QPushButton(self.tab_INIT_IDLE_H)
        self.pushButton_TAB2_JobID_Result.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_TAB2_JobID_Result.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_TAB2_JobID_Result.setObjectName("pushButton_TAB2_JobID_Result")
        self.verticalLayout_17.addWidget(self.pushButton_TAB2_JobID_Result)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        self.horizontalLayout_17.addLayout(self.verticalLayout_18)
        self.frame_TAB2_List_and_Slider = QtWidgets.QFrame(self.tab_INIT_IDLE_H)
        self.frame_TAB2_List_and_Slider.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TAB2_List_and_Slider.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_TAB2_List_and_Slider.setObjectName("frame_TAB2_List_and_Slider")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_TAB2_List_and_Slider)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_4 = QtWidgets.QFrame(self.frame_TAB2_List_and_Slider)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_TAB2_Shots = QtWidgets.QLabel(self.frame_4)
        self.label_TAB2_Shots.setObjectName("label_TAB2_Shots")
        self.gridLayout_20.addWidget(self.label_TAB2_Shots, 3, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_14.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.radioButton_TAB2_Slider_1_OK = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_TAB2_Slider_1_OK.setChecked(True)
        self.radioButton_TAB2_Slider_1_OK.setObjectName("radioButton_TAB2_Slider_1_OK")
        self.horizontalLayout_7.addWidget(self.radioButton_TAB2_Slider_1_OK)
        self.horizontalSlider_TAB2_IDLE = QtWidgets.QSlider(self.frame_4)
        self.horizontalSlider_TAB2_IDLE.setEnabled(False)
        self.horizontalSlider_TAB2_IDLE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_TAB2_IDLE.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_TAB2_IDLE.setObjectName("horizontalSlider_TAB2_IDLE")
        self.horizontalLayout_7.addWidget(self.horizontalSlider_TAB2_IDLE)
        self.gridLayout_14.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_18.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_18.addWidget(self.label_5)
        self.gridLayout_14.addLayout(self.horizontalLayout_18, 2, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_14, 0, 0, 1, 2)
        self.lineEdit_TAB2_Shots = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_TAB2_Shots.setInputMask("")
        self.lineEdit_TAB2_Shots.setObjectName("lineEdit_TAB2_Shots")
        self.gridLayout_20.addWidget(self.lineEdit_TAB2_Shots, 3, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButton_TAB2_ListWidget_1_OK = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_TAB2_ListWidget_1_OK.setObjectName("radioButton_TAB2_ListWidget_1_OK")
        self.horizontalLayout_8.addWidget(self.radioButton_TAB2_ListWidget_1_OK)
        self.listWidget_TAB2_IDLE = QtWidgets.QListWidget(self.frame_4)
        self.listWidget_TAB2_IDLE.setEnabled(False)
        self.listWidget_TAB2_IDLE.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_TAB2_IDLE.setObjectName("listWidget_TAB2_IDLE")
        self.horizontalLayout_8.addWidget(self.listWidget_TAB2_IDLE)
        self.gridLayout_20.addLayout(self.horizontalLayout_8, 1, 0, 1, 2)
        self.horizontalLayout_13.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_TAB2_List_and_Slider)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.lineEdit_TAB2_OptLevel = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_TAB2_OptLevel.setInputMask("")
        self.lineEdit_TAB2_OptLevel.setObjectName("lineEdit_TAB2_OptLevel")
        self.gridLayout_16.addWidget(self.lineEdit_TAB2_OptLevel, 2, 1, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_13.addWidget(self.label_2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.radioButton_TAB2_Slider_2_OK = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_TAB2_Slider_2_OK.setChecked(True)
        self.radioButton_TAB2_Slider_2_OK.setObjectName("radioButton_TAB2_Slider_2_OK")
        self.horizontalLayout_12.addWidget(self.radioButton_TAB2_Slider_2_OK)
        self.horizontalSlider_TAB2_INIT = QtWidgets.QSlider(self.frame_5)
        self.horizontalSlider_TAB2_INIT.setEnabled(False)
        self.horizontalSlider_TAB2_INIT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_TAB2_INIT.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_TAB2_INIT.setObjectName("horizontalSlider_TAB2_INIT")
        self.horizontalLayout_12.addWidget(self.horizontalSlider_TAB2_INIT)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.verticalLayout_15.addLayout(self.verticalLayout_13)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_19.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_19.addWidget(self.label_7)
        self.verticalLayout_15.addLayout(self.horizontalLayout_19)
        self.gridLayout_16.addLayout(self.verticalLayout_15, 0, 0, 1, 2)
        self.label_TAB2_OptLevel = QtWidgets.QLabel(self.frame_5)
        self.label_TAB2_OptLevel.setObjectName("label_TAB2_OptLevel")
        self.gridLayout_16.addWidget(self.label_TAB2_OptLevel, 2, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.radioButton_TAB2_ListWidget_2_OK = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_TAB2_ListWidget_2_OK.setObjectName("radioButton_TAB2_ListWidget_2_OK")
        self.horizontalLayout_11.addWidget(self.radioButton_TAB2_ListWidget_2_OK)
        self.listWidget_TAB2_INIT = QtWidgets.QListWidget(self.frame_5)
        self.listWidget_TAB2_INIT.setEnabled(False)
        self.listWidget_TAB2_INIT.setObjectName("listWidget_TAB2_INIT")
        self.horizontalLayout_11.addWidget(self.listWidget_TAB2_INIT)
        self.gridLayout_16.addLayout(self.horizontalLayout_11, 1, 0, 1, 2)
        self.horizontalLayout_13.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_TAB2_List_and_Slider)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_TAB2_Alpha = QtWidgets.QLabel(self.frame_6)
        self.label_TAB2_Alpha.setObjectName("label_TAB2_Alpha")
        self.gridLayout_17.addWidget(self.label_TAB2_Alpha, 2, 0, 1, 1)
        self.lineEdit_TAB2_Alpha = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_TAB2_Alpha.setObjectName("lineEdit_TAB2_Alpha")
        self.gridLayout_17.addWidget(self.lineEdit_TAB2_Alpha, 2, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.radioButton_TAB2_ListWidget_3_OK = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_TAB2_ListWidget_3_OK.setObjectName("radioButton_TAB2_ListWidget_3_OK")
        self.horizontalLayout_9.addWidget(self.radioButton_TAB2_ListWidget_3_OK)
        self.listWidget_TAB2_H = QtWidgets.QListWidget(self.frame_6)
        self.listWidget_TAB2_H.setEnabled(False)
        self.listWidget_TAB2_H.setObjectName("listWidget_TAB2_H")
        self.horizontalLayout_9.addWidget(self.listWidget_TAB2_H)
        self.gridLayout_17.addLayout(self.horizontalLayout_9, 1, 0, 1, 2)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_14.addWidget(self.label_3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.radioButton_TAB2_Slider_3_OK = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_TAB2_Slider_3_OK.setChecked(True)
        self.radioButton_TAB2_Slider_3_OK.setObjectName("radioButton_TAB2_Slider_3_OK")
        self.horizontalLayout_10.addWidget(self.radioButton_TAB2_Slider_3_OK)
        self.horizontalSlider_TAB2_H = QtWidgets.QSlider(self.frame_6)
        self.horizontalSlider_TAB2_H.setEnabled(False)
        self.horizontalSlider_TAB2_H.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_TAB2_H.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_TAB2_H.setObjectName("horizontalSlider_TAB2_H")
        self.horizontalLayout_10.addWidget(self.horizontalSlider_TAB2_H)
        self.verticalLayout_14.addLayout(self.horizontalLayout_10)
        self.verticalLayout_19.addLayout(self.verticalLayout_14)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_20.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_20.addWidget(self.label_9)
        self.verticalLayout_19.addLayout(self.horizontalLayout_20)
        self.gridLayout_17.addLayout(self.verticalLayout_19, 0, 0, 1, 2)
        self.horizontalLayout_13.addWidget(self.frame_6)
        self.gridLayout_4.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.checkBox_TAB2_bool_barriers = QtWidgets.QCheckBox(self.frame_TAB2_List_and_Slider)
        self.checkBox_TAB2_bool_barriers.setChecked(True)
        self.checkBox_TAB2_bool_barriers.setObjectName("checkBox_TAB2_bool_barriers")
        self.horizontalLayout_14.addWidget(self.checkBox_TAB2_bool_barriers)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.pushButton_TAB2_Generate_Scheme = QtWidgets.QPushButton(self.frame_TAB2_List_and_Slider)
        self.pushButton_TAB2_Generate_Scheme.setEnabled(False)
        self.pushButton_TAB2_Generate_Scheme.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_TAB2_Generate_Scheme.setObjectName("pushButton_TAB2_Generate_Scheme")
        self.horizontalLayout_14.addWidget(self.pushButton_TAB2_Generate_Scheme)
        self.gridLayout_4.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.horizontalLayout_17.addWidget(self.frame_TAB2_List_and_Slider)
        self.gridLayout_18.addLayout(self.horizontalLayout_17, 0, 0, 1, 1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.pushButton_TAB2_Clear_Output = QtWidgets.QPushButton(self.tab_INIT_IDLE_H)
        self.pushButton_TAB2_Clear_Output.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_TAB2_Clear_Output.setObjectName("pushButton_TAB2_Clear_Output")
        self.horizontalLayout_15.addWidget(self.pushButton_TAB2_Clear_Output)
        self.verticalLayout_16.addLayout(self.horizontalLayout_15)
        self.textEdit_TAB2 = QtWidgets.QTextEdit(self.tab_INIT_IDLE_H)
        self.textEdit_TAB2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEdit_TAB2.setReadOnly(True)
        self.textEdit_TAB2.setObjectName("textEdit_TAB2")
        self.verticalLayout_16.addWidget(self.textEdit_TAB2)
        self.gridLayout_18.addLayout(self.verticalLayout_16, 1, 0, 1, 1)
        self.tabWidget_PARENT.addTab(self.tab_INIT_IDLE_H, "")
        self.tab_QRNG = QtWidgets.QWidget()
        self.tab_QRNG.setObjectName("tab_QRNG")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_QRNG)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame = QtWidgets.QFrame(self.tab_QRNG)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_QRNG_RadioButtons = QtWidgets.QFrame(self.frame)
        self.frame_QRNG_RadioButtons.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_QRNG_RadioButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_QRNG_RadioButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_QRNG_RadioButtons.setObjectName("frame_QRNG_RadioButtons")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_QRNG_RadioButtons)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_QRNG_Check = QtWidgets.QRadioButton(self.frame_QRNG_RadioButtons)
        self.radioButton_QRNG_Check.setChecked(True)
        self.radioButton_QRNG_Check.setObjectName("radioButton_QRNG_Check")
        self.horizontalLayout_5.addWidget(self.radioButton_QRNG_Check)
        self.radioButton_QRNG_Simulator_Check = QtWidgets.QRadioButton(self.frame_QRNG_RadioButtons)
        self.radioButton_QRNG_Simulator_Check.setEnabled(True)
        self.radioButton_QRNG_Simulator_Check.setObjectName("radioButton_QRNG_Simulator_Check")
        self.horizontalLayout_5.addWidget(self.radioButton_QRNG_Simulator_Check)
        self.radioButton_NIST_Check = QtWidgets.QRadioButton(self.frame_QRNG_RadioButtons)
        self.radioButton_NIST_Check.setObjectName("radioButton_NIST_Check")
        self.horizontalLayout_5.addWidget(self.radioButton_NIST_Check)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_QRNG_RadioButtons, 0, 0, 1, 1)
        self.frame_QRNG_Simulator = QtWidgets.QFrame(self.frame)
        self.frame_QRNG_Simulator.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_QRNG_Simulator.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_QRNG_Simulator.setObjectName("frame_QRNG_Simulator")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_QRNG_Simulator)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.radioButton_QRNG_Sim_Slider_OK = QtWidgets.QRadioButton(self.frame_QRNG_Simulator)
        self.radioButton_QRNG_Sim_Slider_OK.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_QRNG_Sim_Slider_OK.setChecked(True)
        self.radioButton_QRNG_Sim_Slider_OK.setObjectName("radioButton_QRNG_Sim_Slider_OK")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioButton_QRNG_Sim_Slider_OK)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_QRNG_SIMULATOR_Num_of_Qubits = QtWidgets.QLabel(self.frame_QRNG_Simulator)
        self.label_QRNG_SIMULATOR_Num_of_Qubits.setAlignment(QtCore.Qt.AlignCenter)
        self.label_QRNG_SIMULATOR_Num_of_Qubits.setObjectName("label_QRNG_SIMULATOR_Num_of_Qubits")
        self.verticalLayout_7.addWidget(self.label_QRNG_SIMULATOR_Num_of_Qubits)
        self.horizontalSlider_QRNG_SIMULATOR_Num_of_Qubits = QtWidgets.QSlider(self.frame_QRNG_Simulator)
        self.horizontalSlider_QRNG_SIMULATOR_Num_of_Qubits.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_QRNG_SIMULATOR_Num_of_Qubits.setMinimum(1)
        self.horizontalSlider_QRNG_SIMULATOR_Num_of_Qubits.setMaximum(10)
        self.horizontalSlider_QRNG_SIMULATOR_Num_of_Qubits.setPageStep(1)
        self.horizontalSlider_QRNG_SIMULATOR_Num_of_Qubits.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_QRNG_SIMULATOR_Num_of_Qubits.setObjectName("horizontalSlider_QRNG_SIMULATOR_Num_of_Qubits")
        self.verticalLayout_7.addWidget(self.horizontalSlider_QRNG_SIMULATOR_Num_of_Qubits)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_QRNG_SIMULATOR_Num_of_Qubits_2 = QtWidgets.QLabel(self.frame_QRNG_Simulator)
        self.label_QRNG_SIMULATOR_Num_of_Qubits_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_QRNG_SIMULATOR_Num_of_Qubits_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_QRNG_SIMULATOR_Num_of_Qubits_2.setObjectName("label_QRNG_SIMULATOR_Num_of_Qubits_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_QRNG_SIMULATOR_Num_of_Qubits_2)
        self.label_QRNG_SIMULATOR_Qubits = QtWidgets.QLabel(self.frame_QRNG_Simulator)
        self.label_QRNG_SIMULATOR_Qubits.setObjectName("label_QRNG_SIMULATOR_Qubits")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_QRNG_SIMULATOR_Qubits)
        self.verticalLayout_7.addLayout(self.formLayout)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.formLayout_4)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.radioButton_QRNG_Sim_listWidget_OK = QtWidgets.QRadioButton(self.frame_QRNG_Simulator)
        self.radioButton_QRNG_Sim_listWidget_OK.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_QRNG_Sim_listWidget_OK.setObjectName("radioButton_QRNG_Sim_listWidget_OK")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioButton_QRNG_Sim_listWidget_OK)
        self.listWidget_QRNG_Sim_Check_Qubits = QtWidgets.QListWidget(self.frame_QRNG_Simulator)
        self.listWidget_QRNG_Sim_Check_Qubits.setEnabled(False)
        self.listWidget_QRNG_Sim_Check_Qubits.setObjectName("listWidget_QRNG_Sim_Check_Qubits")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.listWidget_QRNG_Sim_Check_Qubits)
        self.verticalLayout_8.addLayout(self.formLayout_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.pushButton_QRNG_SIMULATO_Start = QtWidgets.QPushButton(self.frame_QRNG_Simulator)
        self.pushButton_QRNG_SIMULATO_Start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_QRNG_SIMULATO_Start.setObjectName("pushButton_QRNG_SIMULATO_Start")
        self.verticalLayout_9.addWidget(self.pushButton_QRNG_SIMULATO_Start)
        self.gridLayout_3.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_QRNG_Simulator, 0, 1, 2, 1)
        self.frame_QRNG = QtWidgets.QFrame(self.frame)
        self.frame_QRNG.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_QRNG.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_QRNG.setObjectName("frame_QRNG")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_QRNG)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_QRNG_QPU_Select = QtWidgets.QLabel(self.frame_QRNG)
        self.label_QRNG_QPU_Select.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_QRNG_QPU_Select.setObjectName("label_QRNG_QPU_Select")
        self.verticalLayout_2.addWidget(self.label_QRNG_QPU_Select)
        self.comboBox_QRNG_QPU_List = QtWidgets.QComboBox(self.frame_QRNG)
        self.comboBox_QRNG_QPU_List.setEnabled(False)
        self.comboBox_QRNG_QPU_List.setEditable(False)
        self.comboBox_QRNG_QPU_List.setObjectName("comboBox_QRNG_QPU_List")
        self.verticalLayout_2.addWidget(self.comboBox_QRNG_QPU_List)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.label_QRNG_JobID = QtWidgets.QLabel(self.frame_QRNG)
        self.label_QRNG_JobID.setAlignment(QtCore.Qt.AlignCenter)
        self.label_QRNG_JobID.setObjectName("label_QRNG_JobID")
        self.verticalLayout_2.addWidget(self.label_QRNG_JobID)
        self.lineEdit_QRNG_JobID = QtWidgets.QLineEdit(self.frame_QRNG)
        self.lineEdit_QRNG_JobID.setClearButtonEnabled(True)
        self.lineEdit_QRNG_JobID.setObjectName("lineEdit_QRNG_JobID")
        self.verticalLayout_2.addWidget(self.lineEdit_QRNG_JobID)
        self.pushButton_QRNG_JobID_Check = QtWidgets.QPushButton(self.frame_QRNG)
        self.pushButton_QRNG_JobID_Check.setEnabled(True)
        self.pushButton_QRNG_JobID_Check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_QRNG_JobID_Check.setObjectName("pushButton_QRNG_JobID_Check")
        self.verticalLayout_2.addWidget(self.pushButton_QRNG_JobID_Check)
        self.pushButton_QRNG_JobID_Cancel = QtWidgets.QPushButton(self.frame_QRNG)
        self.pushButton_QRNG_JobID_Cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_QRNG_JobID_Cancel.setObjectName("pushButton_QRNG_JobID_Cancel")
        self.verticalLayout_2.addWidget(self.pushButton_QRNG_JobID_Cancel)
        self.pushButton_QRNG_JobID_Download = QtWidgets.QPushButton(self.frame_QRNG)
        self.pushButton_QRNG_JobID_Download.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_QRNG_JobID_Download.setObjectName("pushButton_QRNG_JobID_Download")
        self.verticalLayout_2.addWidget(self.pushButton_QRNG_JobID_Download)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_QRNG_Slider_OK = QtWidgets.QRadioButton(self.frame_QRNG)
        self.radioButton_QRNG_Slider_OK.setMinimumSize(QtCore.QSize(45, 0))
        self.radioButton_QRNG_Slider_OK.setMaximumSize(QtCore.QSize(45, 111111))
        self.radioButton_QRNG_Slider_OK.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_QRNG_Slider_OK.setChecked(True)
        self.radioButton_QRNG_Slider_OK.setObjectName("radioButton_QRNG_Slider_OK")
        self.horizontalLayout.addWidget(self.radioButton_QRNG_Slider_OK)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2_QRNG_Num_of_Qubits = QtWidgets.QLabel(self.frame_QRNG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2_QRNG_Num_of_Qubits.sizePolicy().hasHeightForWidth())
        self.label_2_QRNG_Num_of_Qubits.setSizePolicy(sizePolicy)
        self.label_2_QRNG_Num_of_Qubits.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2_QRNG_Num_of_Qubits.setObjectName("label_2_QRNG_Num_of_Qubits")
        self.verticalLayout_3.addWidget(self.label_2_QRNG_Num_of_Qubits)
        self.horizontalSlider_QRNG_Num_of_Qubits = QtWidgets.QSlider(self.frame_QRNG)
        self.horizontalSlider_QRNG_Num_of_Qubits.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_QRNG_Num_of_Qubits.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_QRNG_Num_of_Qubits.setSizePolicy(sizePolicy)
        self.horizontalSlider_QRNG_Num_of_Qubits.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_QRNG_Num_of_Qubits.setMaximum(0)
        self.horizontalSlider_QRNG_Num_of_Qubits.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_QRNG_Num_of_Qubits.setObjectName("horizontalSlider_QRNG_Num_of_Qubits")
        self.verticalLayout_3.addWidget(self.horizontalSlider_QRNG_Num_of_Qubits)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_QRNG_Num_of_Qubits = QtWidgets.QLabel(self.frame_QRNG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_QRNG_Num_of_Qubits.sizePolicy().hasHeightForWidth())
        self.label_QRNG_Num_of_Qubits.setSizePolicy(sizePolicy)
        self.label_QRNG_Num_of_Qubits.setMinimumSize(QtCore.QSize(80, 0))
        self.label_QRNG_Num_of_Qubits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_QRNG_Num_of_Qubits.setObjectName("label_QRNG_Num_of_Qubits")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_QRNG_Num_of_Qubits)
        self.label_QRNG_Qubits = QtWidgets.QLabel(self.frame_QRNG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_QRNG_Qubits.sizePolicy().hasHeightForWidth())
        self.label_QRNG_Qubits.setSizePolicy(sizePolicy)
        self.label_QRNG_Qubits.setObjectName("label_QRNG_Qubits")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_QRNG_Qubits)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_QRNG_listWidget_OK = QtWidgets.QRadioButton(self.frame_QRNG)
        self.radioButton_QRNG_listWidget_OK.setMinimumSize(QtCore.QSize(45, 0))
        self.radioButton_QRNG_listWidget_OK.setMaximumSize(QtCore.QSize(45, 16777215))
        self.radioButton_QRNG_listWidget_OK.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_QRNG_listWidget_OK.setObjectName("radioButton_QRNG_listWidget_OK")
        self.verticalLayout_4.addWidget(self.radioButton_QRNG_listWidget_OK)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.listWidget_QRNG_Check_Qubits = QtWidgets.QListWidget(self.frame_QRNG)
        self.listWidget_QRNG_Check_Qubits.setEnabled(False)
        self.listWidget_QRNG_Check_Qubits.setObjectName("listWidget_QRNG_Check_Qubits")
        self.horizontalLayout_3.addWidget(self.listWidget_QRNG_Check_Qubits)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_ALPHA = QtWidgets.QLabel(self.frame_QRNG)
        self.label_ALPHA.setObjectName("label_ALPHA")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ALPHA)
        self.lineEdit_ALPHA = QtWidgets.QLineEdit(self.frame_QRNG)
        self.lineEdit_ALPHA.setEnabled(True)
        self.lineEdit_ALPHA.setClearButtonEnabled(True)
        self.lineEdit_ALPHA.setObjectName("lineEdit_ALPHA")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ALPHA)
        self.label_QRNG_Shots = QtWidgets.QLabel(self.frame_QRNG)
        self.label_QRNG_Shots.setObjectName("label_QRNG_Shots")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_QRNG_Shots)
        self.label_QRNG_OptLevel = QtWidgets.QLabel(self.frame_QRNG)
        self.label_QRNG_OptLevel.setObjectName("label_QRNG_OptLevel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_QRNG_OptLevel)
        self.lineEdit_QRNG_Shots = QtWidgets.QLineEdit(self.frame_QRNG)
        self.lineEdit_QRNG_Shots.setClearButtonEnabled(True)
        self.lineEdit_QRNG_Shots.setObjectName("lineEdit_QRNG_Shots")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_QRNG_Shots)
        self.lineEdit_QRNG_OptLevel = QtWidgets.QLineEdit(self.frame_QRNG)
        self.lineEdit_QRNG_OptLevel.setClearButtonEnabled(True)
        self.lineEdit_QRNG_OptLevel.setObjectName("lineEdit_QRNG_OptLevel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_QRNG_OptLevel)
        self.verticalLayout_11.addLayout(self.formLayout_3)
        self.pushButton_QRNG_Start = QtWidgets.QPushButton(self.frame_QRNG)
        self.pushButton_QRNG_Start.setEnabled(False)
        self.pushButton_QRNG_Start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_QRNG_Start.setObjectName("pushButton_QRNG_Start")
        self.verticalLayout_11.addWidget(self.pushButton_QRNG_Start)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.gridLayout_15.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_QRNG, 1, 0, 2, 1)
        self.frame_NIST = QtWidgets.QFrame(self.frame)
        self.frame_NIST.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_NIST.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_NIST.setObjectName("frame_NIST")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_NIST)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_NIST_Key_Length = QtWidgets.QLineEdit(self.frame_NIST)
        self.lineEdit_NIST_Key_Length.setClearButtonEnabled(True)
        self.lineEdit_NIST_Key_Length.setObjectName("lineEdit_NIST_Key_Length")
        self.gridLayout_5.addWidget(self.lineEdit_NIST_Key_Length, 1, 1, 1, 1)
        self.lineEdit_NIST_Parameters_on_Default = QtWidgets.QLineEdit(self.frame_NIST)
        self.lineEdit_NIST_Parameters_on_Default.setEnabled(True)
        self.lineEdit_NIST_Parameters_on_Default.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.lineEdit_NIST_Parameters_on_Default.setReadOnly(True)
        self.lineEdit_NIST_Parameters_on_Default.setObjectName("lineEdit_NIST_Parameters_on_Default")
        self.gridLayout_5.addWidget(self.lineEdit_NIST_Parameters_on_Default, 3, 1, 1, 1)
        self.lineEdit_NIST_Tests_Supplys = QtWidgets.QLineEdit(self.frame_NIST)
        self.lineEdit_NIST_Tests_Supplys.setEnabled(True)
        self.lineEdit_NIST_Tests_Supplys.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.lineEdit_NIST_Tests_Supplys.setReadOnly(True)
        self.lineEdit_NIST_Tests_Supplys.setObjectName("lineEdit_NIST_Tests_Supplys")
        self.gridLayout_5.addWidget(self.lineEdit_NIST_Tests_Supplys, 2, 1, 1, 1)
        self.label_NIST_Directory_to_Dataset = QtWidgets.QLabel(self.frame_NIST)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.label_NIST_Directory_to_Dataset.setFont(font)
        self.label_NIST_Directory_to_Dataset.setObjectName("label_NIST_Directory_to_Dataset")
        self.gridLayout_5.addWidget(self.label_NIST_Directory_to_Dataset, 0, 0, 1, 1)
        self.pushButton_NIST_Start = QtWidgets.QPushButton(self.frame_NIST)
        self.pushButton_NIST_Start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_NIST_Start.setObjectName("pushButton_NIST_Start")
        self.gridLayout_5.addWidget(self.pushButton_NIST_Start, 6, 0, 1, 2)
        self.lineEdit_NIST_Directory_to_Dataset = QtWidgets.QLineEdit(self.frame_NIST)
        self.lineEdit_NIST_Directory_to_Dataset.setText("")
        self.lineEdit_NIST_Directory_to_Dataset.setClearButtonEnabled(True)
        self.lineEdit_NIST_Directory_to_Dataset.setObjectName("lineEdit_NIST_Directory_to_Dataset")
        self.gridLayout_5.addWidget(self.lineEdit_NIST_Directory_to_Dataset, 0, 1, 1, 1)
        self.label_NIST_Key_Length = QtWidgets.QLabel(self.frame_NIST)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.label_NIST_Key_Length.setFont(font)
        self.label_NIST_Key_Length.setObjectName("label_NIST_Key_Length")
        self.gridLayout_5.addWidget(self.label_NIST_Key_Length, 1, 0, 1, 1)
        self.label_NIST_Tests_Supplys = QtWidgets.QLabel(self.frame_NIST)
        self.label_NIST_Tests_Supplys.setObjectName("label_NIST_Tests_Supplys")
        self.gridLayout_5.addWidget(self.label_NIST_Tests_Supplys, 2, 0, 1, 1)
        self.label_NIST_Num_of_Bitstream = QtWidgets.QLabel(self.frame_NIST)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.label_NIST_Num_of_Bitstream.setFont(font)
        self.label_NIST_Num_of_Bitstream.setObjectName("label_NIST_Num_of_Bitstream")
        self.gridLayout_5.addWidget(self.label_NIST_Num_of_Bitstream, 4, 0, 1, 1)
        self.lineEdit_NIST_Format_of_Data = QtWidgets.QLineEdit(self.frame_NIST)
        self.lineEdit_NIST_Format_of_Data.setEnabled(True)
        self.lineEdit_NIST_Format_of_Data.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.lineEdit_NIST_Format_of_Data.setWhatsThis("")
        self.lineEdit_NIST_Format_of_Data.setReadOnly(True)
        self.lineEdit_NIST_Format_of_Data.setObjectName("lineEdit_NIST_Format_of_Data")
        self.gridLayout_5.addWidget(self.lineEdit_NIST_Format_of_Data, 5, 1, 1, 1)
        self.lineEdit_NIST_Num_of_Bitstream = QtWidgets.QLineEdit(self.frame_NIST)
        self.lineEdit_NIST_Num_of_Bitstream.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_NIST_Num_of_Bitstream.setClearButtonEnabled(True)
        self.lineEdit_NIST_Num_of_Bitstream.setObjectName("lineEdit_NIST_Num_of_Bitstream")
        self.gridLayout_5.addWidget(self.lineEdit_NIST_Num_of_Bitstream, 4, 1, 1, 1)
        self.label_NIST_Parameters_on_Default = QtWidgets.QLabel(self.frame_NIST)
        self.label_NIST_Parameters_on_Default.setObjectName("label_NIST_Parameters_on_Default")
        self.gridLayout_5.addWidget(self.label_NIST_Parameters_on_Default, 3, 0, 1, 1)
        self.label_NIST_Format_of_Data = QtWidgets.QLabel(self.frame_NIST)
        self.label_NIST_Format_of_Data.setObjectName("label_NIST_Format_of_Data")
        self.gridLayout_5.addWidget(self.label_NIST_Format_of_Data, 5, 0, 1, 1)
        self.pushButton_Path_for_NIST_Dialog = QtWidgets.QPushButton(self.frame_NIST)
        self.pushButton_Path_for_NIST_Dialog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Path_for_NIST_Dialog.setObjectName("pushButton_Path_for_NIST_Dialog")
        self.gridLayout_5.addWidget(self.pushButton_Path_for_NIST_Dialog, 0, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.gridLayout_8.addWidget(self.frame_NIST, 2, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.frame_QRNG_Output = QtWidgets.QFrame(self.frame)
        self.frame_QRNG_Output.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_QRNG_Output.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_QRNG_Output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_QRNG_Output.setObjectName("frame_QRNG_Output")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_QRNG_Output)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.pushButton_QRNG_Clear_Output = QtWidgets.QPushButton(self.frame_QRNG_Output)
        self.pushButton_QRNG_Clear_Output.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_QRNG_Clear_Output.setObjectName("pushButton_QRNG_Clear_Output")
        self.horizontalLayout_16.addWidget(self.pushButton_QRNG_Clear_Output)
        self.gridLayout_7.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.textEdit_QRNG_Output = QtWidgets.QTextEdit(self.frame_QRNG_Output)
        self.textEdit_QRNG_Output.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_QRNG_Output.setReadOnly(True)
        self.textEdit_QRNG_Output.setObjectName("textEdit_QRNG_Output")
        self.gridLayout_7.addWidget(self.textEdit_QRNG_Output, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_QRNG_Output, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_10)
        self.tabWidget_PARENT.addTab(self.tab_QRNG, "")
        self.tab_QKD = QtWidgets.QWidget()
        self.tab_QKD.setObjectName("tab_QKD")
        self.tabWidget_PARENT.addTab(self.tab_QKD, "")
        self.tab_Fourie = QtWidgets.QWidget()
        self.tab_Fourie.setObjectName("tab_Fourie")
        self.tabWidget_PARENT.addTab(self.tab_Fourie, "")
        self.gridLayout_19.addWidget(self.tabWidget_PARENT, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_PARENT.setCurrentIndex(0)
        self.comboBox_INFO_QPU_List.setCurrentIndex(-1)
        self.pushButton_INFO_Clear_Output.clicked.connect(self.textEdit_Console_Output.clear)
        self.horizontalSlider_INFO_Num_of_Qubits.valueChanged['int'].connect(self.label_INFO_Selected_Qubit.setNum)
        self.pushButton_QRNG_Clear_Output.clicked.connect(self.textEdit_QRNG_Output.clear)
        self.horizontalSlider_QRNG_Num_of_Qubits.valueChanged['int'].connect(self.label_QRNG_Num_of_Qubits.setNum)
        self.horizontalSlider_QRNG_SIMULATOR_Num_of_Qubits.valueChanged['int'].connect(self.label_QRNG_SIMULATOR_Num_of_Qubits_2.setNum)
        self.pushButton_TAB2_Clear_Output.clicked.connect(self.textEdit_TAB2.clear)
        self.horizontalSlider_TAB2_IDLE.valueChanged['int'].connect(self.label_4.setNum)
        self.horizontalSlider_TAB2_INIT.valueChanged['int'].connect(self.label_6.setNum)
        self.horizontalSlider_TAB2_H.valueChanged['int'].connect(self.label_8.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QIS_Benchmark_v.0.3"))
        self.label_API_Token.setText(_translate("MainWindow", "API Token:"))
        self.pushButton_INFO_Get_Info_on_Qubit.setText(_translate("MainWindow", "Дополнительные сведения"))
        self.label_INFO_QPU_Select.setText(_translate("MainWindow", "Выберите КВУ:"))
        self.label_INFO_Selected_Qubit.setText(_translate("MainWindow", "0"))
        self.label_INFO_Num_of_Qubits.setText(_translate("MainWindow", "Выберите кубит:"))
        self.label_INFO_qubits.setText(_translate("MainWindow", "Кубит: "))
        self.label_Chennel.setText(_translate("MainWindow", "Channel:"))
        self.label_Instance.setText(_translate("MainWindow", "Instance:"))
        self.pushButton_Apply_API_Token.setText(_translate("MainWindow", "Подтвердить"))
        self.radioButton_PROFESSIONAL.setText(_translate("MainWindow", "Profi"))
        self.radioButton_BASE.setText(_translate("MainWindow", "Lox"))
        self.label_BaseProfi.setText(_translate("MainWindow", "Режим работы:"))
        self.pushButton_QPU_Available.setText(_translate("MainWindow", "Доступные КВУ"))
        self.pushButton_QPU_Characteristics.setText(_translate("MainWindow", "Дополнительная информация"))
        self.pushButton_INFO_Clear_Output.setText(_translate("MainWindow", "Очистить"))
        self.label_Console_Output.setText(_translate("MainWindow", "Console:"))
        self.tabWidget_PARENT.setTabText(self.tabWidget_PARENT.indexOf(self.tab_INFO), _translate("MainWindow", "Инициализация"))
        self.label_TAB2_QPU_List.setText(_translate("MainWindow", "Выберите КВУ:"))
        self.label_TAB2_JobID.setText(_translate("MainWindow", "Job ID:"))
        self.pushButton_TAB2_JobID_Info.setText(_translate("MainWindow", "Сведения"))
        self.pushButton_TAB2_JobID_Cancell.setText(_translate("MainWindow", "Отменить"))
        self.pushButton_TAB2_JobID_Result.setText(_translate("MainWindow", "Результаты"))
        self.label_TAB2_Shots.setText(_translate("MainWindow", "Shots: "))
        self.label.setText(_translate("MainWindow", "[IDLE]<=>[MESAURE]"))
        self.radioButton_TAB2_Slider_1_OK.setText(_translate("MainWindow", "1"))
        self.label_4.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Кубит"))
        self.lineEdit_TAB2_Shots.setText(_translate("MainWindow", "20000"))
        self.radioButton_TAB2_ListWidget_1_OK.setText(_translate("MainWindow", "2"))
        self.lineEdit_TAB2_OptLevel.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "[INIT]"))
        self.radioButton_TAB2_Slider_2_OK.setText(_translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Кубит"))
        self.label_TAB2_OptLevel.setText(_translate("MainWindow", "Opt. Level: "))
        self.radioButton_TAB2_ListWidget_2_OK.setText(_translate("MainWindow", "2"))
        self.label_TAB2_Alpha.setText(_translate("MainWindow", "Alpha: "))
        self.lineEdit_TAB2_Alpha.setText(_translate("MainWindow", "0.01"))
        self.radioButton_TAB2_ListWidget_3_OK.setText(_translate("MainWindow", "2"))
        self.label_3.setText(_translate("MainWindow", "[H]"))
        self.radioButton_TAB2_Slider_3_OK.setText(_translate("MainWindow", "1"))
        self.label_8.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Кубит"))
        self.checkBox_TAB2_bool_barriers.setText(_translate("MainWindow", "Использовать барьеры"))
        self.pushButton_TAB2_Generate_Scheme.setText(_translate("MainWindow", "Выполнить"))
        self.pushButton_TAB2_Clear_Output.setText(_translate("MainWindow", "Очистить"))
        self.tabWidget_PARENT.setTabText(self.tabWidget_PARENT.indexOf(self.tab_INIT_IDLE_H), _translate("MainWindow", "INIT-IDLE"))
        self.radioButton_QRNG_Check.setText(_translate("MainWindow", "КГСЧ"))
        self.radioButton_QRNG_Simulator_Check.setText(_translate("MainWindow", "Симулятор КГСЧ"))
        self.radioButton_NIST_Check.setText(_translate("MainWindow", "NIST"))
        self.radioButton_QRNG_Sim_Slider_OK.setText(_translate("MainWindow", "1"))
        self.label_QRNG_SIMULATOR_Num_of_Qubits.setText(_translate("MainWindow", "Размер регистра:"))
        self.label_QRNG_SIMULATOR_Num_of_Qubits_2.setText(_translate("MainWindow", "1"))
        self.label_QRNG_SIMULATOR_Qubits.setText(_translate("MainWindow", "Кубит"))
        self.radioButton_QRNG_Sim_listWidget_OK.setText(_translate("MainWindow", "2"))
        self.pushButton_QRNG_SIMULATO_Start.setText(_translate("MainWindow", "Запустить КГСЧ на симуляторе"))
        self.label_QRNG_QPU_Select.setText(_translate("MainWindow", " Выберите КВУ:"))
        self.label_QRNG_JobID.setText(_translate("MainWindow", "Job ID: "))
        self.pushButton_QRNG_JobID_Check.setText(_translate("MainWindow", "Сведения"))
        self.pushButton_QRNG_JobID_Cancel.setText(_translate("MainWindow", "Отменить"))
        self.pushButton_QRNG_JobID_Download.setText(_translate("MainWindow", "Результаты"))
        self.radioButton_QRNG_Slider_OK.setText(_translate("MainWindow", "1"))
        self.label_2_QRNG_Num_of_Qubits.setText(_translate("MainWindow", "Размер регистра:"))
        self.label_QRNG_Num_of_Qubits.setText(_translate("MainWindow", "0"))
        self.label_QRNG_Qubits.setText(_translate("MainWindow", "Кубит"))
        self.radioButton_QRNG_listWidget_OK.setText(_translate("MainWindow", "2"))
        self.label_ALPHA.setText(_translate("MainWindow", "Alpha: "))
        self.lineEdit_ALPHA.setText(_translate("MainWindow", "0.01"))
        self.label_QRNG_Shots.setText(_translate("MainWindow", "Shots: "))
        self.label_QRNG_OptLevel.setText(_translate("MainWindow", "Opt.Level: "))
        self.lineEdit_QRNG_Shots.setText(_translate("MainWindow", "20000"))
        self.lineEdit_QRNG_OptLevel.setText(_translate("MainWindow", "0"))
        self.pushButton_QRNG_Start.setText(_translate("MainWindow", "Запустить КГСЧ"))
        self.lineEdit_NIST_Key_Length.setText(_translate("MainWindow", "20000"))
        self.lineEdit_NIST_Parameters_on_Default.setText(_translate("MainWindow", "0"))
        self.lineEdit_NIST_Tests_Supplys.setText(_translate("MainWindow", "1"))
        self.label_NIST_Directory_to_Dataset.setText(_translate("MainWindow", "Папка с СП:"))
        self.pushButton_NIST_Start.setText(_translate("MainWindow", "Запустить NIST STS"))
        self.label_NIST_Key_Length.setText(_translate("MainWindow", "Длина СП:"))
        self.label_NIST_Tests_Supplys.setText(_translate("MainWindow", "Покрытие:"))
        self.label_NIST_Num_of_Bitstream.setText(_translate("MainWindow", "\'bitstream\':"))
        self.lineEdit_NIST_Format_of_Data.setText(_translate("MainWindow", "0"))
        self.lineEdit_NIST_Num_of_Bitstream.setText(_translate("MainWindow", "1"))
        self.label_NIST_Parameters_on_Default.setText(_translate("MainWindow", "Параметры:"))
        self.label_NIST_Format_of_Data.setText(_translate("MainWindow", "Формат:"))
        self.pushButton_Path_for_NIST_Dialog.setText(_translate("MainWindow", "Browse"))
        self.pushButton_QRNG_Clear_Output.setText(_translate("MainWindow", "Очистить"))
        self.tabWidget_PARENT.setTabText(self.tabWidget_PARENT.indexOf(self.tab_QRNG), _translate("MainWindow", "КГСЧ"))
        self.tabWidget_PARENT.setTabText(self.tabWidget_PARENT.indexOf(self.tab_QKD), _translate("MainWindow", "ККС ВРК"))
        self.tabWidget_PARENT.setTabText(self.tabWidget_PARENT.indexOf(self.tab_Fourie), _translate("MainWindow", "Фурье"))
        self.menu.setTitle(_translate("MainWindow", "Меню 1"))
        self.menu_2.setTitle(_translate("MainWindow", "Меню 2"))
        self.action.setText(_translate("MainWindow", "Меню 1.1"))
